ServerName localhost
ServerTokens Prod
ServerSignature Off

<VirtualHost *:80>
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        Options -Indexes -MultiViews
        AllowOverride None
        Require all granted
        DirectoryIndex index.php
        FallbackResource /index.php

        <FilesMatch "^\.">
            Require all denied
        </FilesMatch>
        <Files "router.php">
            Require all denied
        </Files>
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
